version: '3.8'
services:
  server:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  client:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
